Repository codesquad-kiosk-max-team-02/kiosk-max, pull requests merged in 2023-06, with the labels that each got.

#2 [FE] chore #1: 개발환경 세팅
  fe/.eslintrc.json
  fe/.gitignore
  fe/.prettierrc.json
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/public/robots.txt
  fe/src/App.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/react-app-env.d.ts
  fe/src/reportWebVitals.ts
  fe/src/setupTests.ts
  fe/tsconfig.json
Labels: 🧑‍💻 FE, chore

#18 [BE] chore #4: swagger 의존성 추가
  be/build.gradle
  be/src/main/resources/application.properties
Labels: 💻 BE, chore

#20 [FE] feat #1: main 상단탭 구현
  fe/src/App.css
  fe/src/App.module.css
  fe/src/App.test.tsx
  fe/src/App.tsx
  fe/src/components/Tab.module.css
  fe/src/components/Tab.tsx
  fe/src/components/TabContainer.module.css
  fe/src/components/TabContainer.tsx
  fe/src/components/TabMenu.module.css
  fe/src/components/TabMenu.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/logo.svg
  fe/src/reset.css
Labels: 🧑‍💻 FE, feat

#22 [BE] feat #21: 클래스 설계
  be/src/main/java/com/codesquad/kiosk/controller/MenuController.java
  be/src/main/java/com/codesquad/kiosk/controller/OrderController.java
  be/src/main/java/com/codesquad/kiosk/domain/Category.java
  be/src/main/java/com/codesquad/kiosk/domain/Menu.java
  be/src/main/java/com/codesquad/kiosk/domain/Option.java
  be/src/main/java/com/codesquad/kiosk/domain/OptionCategory.java
  be/src/main/java/com/codesquad/kiosk/domain/Order.java
  be/src/main/java/com/codesquad/kiosk/domain/OrderMenu.java
  be/src/main/java/com/codesquad/kiosk/repository/MenuRepository.java
  be/src/main/java/com/codesquad/kiosk/repository/OrderRepository.java
  be/src/main/java/com/codesquad/kiosk/service/MenuService.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, feat

#27 [FE] feat #5:상단탭 & 메인화면 UI 및 기능 작업
  fe/package-lock.json
  fe/package.json
  fe/public/assets/americano.jpeg
  fe/public/assets/decaf.jpeg
  fe/public/assets/juice.jpeg
  fe/public/assets/latte.jpeg
  fe/public/assets/tea.jpeg
  fe/public/mockServiceWorker.js
  fe/src/App.tsx
  fe/src/components/Card.module.css
  fe/src/components/Card.tsx
  fe/src/components/MainArea.module.css
  fe/src/components/MainArea.tsx
  fe/src/components/Tab.module.css
  fe/src/components/Tab.tsx
  fe/src/components/TabContainer.tsx
  fe/src/components/TabMenu.tsx
  fe/src/index.tsx
  fe/src/mocks/browser.ts
  fe/src/mocks/handler.ts
  fe/src/utils/types.ts
Labels: 🧑‍💻 FE, feat

#30 [FE] feat : 메인화면과 모달이 연동되는 기능 구현
  fe/public/index.html
  fe/src/App.tsx
  fe/src/components/AddMenu.module.css
  fe/src/components/AddMenu.tsx
  fe/src/components/Card.module.css
  fe/src/components/Card.tsx
  fe/src/components/MainArea.tsx
  fe/src/components/TestBtnForModal.tsx
  fe/src/index.tsx
Labels: 🧑‍💻 FE, feat

#33 chore : 로컬 환경 세팅 h2 의존성추가 , mysql 연결 추가
  be/build.gradle
  be/src/main/resources/application.properties
Labels: 💻 BE, chore

#35 [BE] README 수정 (#34)
  README.md
Labels: docs, 💻 BE

#42 [FE] refactor #23: 메인화면과 모달이 연동되는 기능
  fe/src/components/AddMenu.module.css
  fe/src/components/AddMenu.tsx
  fe/src/components/Card.tsx
  fe/src/components/Modal.tsx
  fe/src/components/OptionButton.module.css
  fe/src/components/OptionButton.tsx
  fe/src/index.tsx
  fe/src/mocks/handler.ts
Labels: 🧑‍💻 FE, refactor

#48 [FE] feat #23: 라우터 제거 및 가격 렌더링 버그 픽스
  fe/src/components/AddMenu.tsx
  fe/src/components/Card.tsx
  fe/src/components/MainArea.tsx
  fe/src/components/Modal.tsx
  fe/src/index.tsx
Labels: 🧑‍💻 FE, feat, refactor

#50 [FE] feat #23: 장바구니 메뉴 추가
  fe/src/App.tsx
  fe/src/components/AddMenu.tsx
  fe/src/components/Cart.module.css
  fe/src/components/Cart.tsx
  fe/src/components/MainArea.tsx
  fe/src/mocks/handler.ts
  fe/src/utils/types.ts
Labels: 🧑‍💻 FE, ✨ feat

#52 [FE] design #23: 장바구니 오른쪽 UI
  fe/src/components/Cart.module.css
  fe/src/components/Cart.tsx
Labels: 🧑‍💻 FE, 🎨 UI

#55 [be] feat #54 : 상단바 카테고리 조회 api
  be/src/main/java/com/codesquad/kiosk/controller/MenuController.java
  be/src/main/java/com/codesquad/kiosk/dto/CategoryResponseDto.java
  be/src/main/java/com/codesquad/kiosk/repository/MenuRepository.java
  be/src/main/java/com/codesquad/kiosk/service/MenuService.java
Labels: 💻 BE, ✨ feat

#56 [FE] feat #44: 주문담기 모달 및 장바구니 연결되는 기능 구현
  fe/public/assets/americano.jpeg
  fe/public/assets/caffe-mocha.jpeg
  fe/public/assets/cappuccino.jpeg
  fe/public/assets/coldbrew.jpeg
  fe/public/assets/espresso.jpeg
  fe/public/favicon.ico
  fe/public/index.html
  fe/public/logo192.png
  fe/public/logo512.png
  fe/public/manifest.json
  fe/src/App.tsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Cart/CartItem.module.css
  fe/src/components/Cart/CartItem.tsx
  fe/src/components/CartItem.module.css
  fe/src/components/CartItem.tsx
  fe/src/components/Main/Card.module.css
  fe/src/components/Main/Card.tsx
  fe/src/components/Main/MainArea.module.css
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Modal/AddMenu.module.css
  fe/src/components/Modal/AddMenu.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/OptionButton.module.css
  fe/src/components/Modal/OptionButton.tsx
  fe/src/components/Tab/Tab.module.css
  fe/src/components/Tab/Tab.tsx
  fe/src/components/Tab/TabMenu.module.css
  fe/src/components/Tab/TabMenu.tsx
  fe/src/index.tsx
  fe/src/mocks/handler.ts
  fe/src/utils/customHook.ts
  fe/src/utils/types.ts
Labels: 🧑‍💻 FE, ✨ feat

#57 [FE] feat #44: 장바구니 전체 취소 및 결제, 타이머
  fe/src/App.tsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Cart/CartItem.module.css
  fe/src/components/Cart/CartItem.tsx
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Modal/AddMenu.module.css
  fe/src/components/Modal/AddMenu.tsx
  fe/src/components/Modal/CardPayment.module.css
  fe/src/components/Modal/CardPayment.tsx
  fe/src/components/Modal/CashPayment.module.css
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/Payment.module.css
  fe/src/components/Modal/Payment.tsx
Labels: 🧑‍💻 FE, ✨ feat, 🎨 UI

#65 [BE] 카테고리별 메뉴 조회 API 구현
  be/src/main/java/com/codesquad/kiosk/controller/MenuController.java
  be/src/main/java/com/codesquad/kiosk/domain/Menu.java
  be/src/main/java/com/codesquad/kiosk/domain/OrderMenu.java
  be/src/main/java/com/codesquad/kiosk/dto/MenusByCategoryResponseDto.java
  be/src/main/java/com/codesquad/kiosk/repository/MenuRepository.java
  be/src/main/java/com/codesquad/kiosk/service/MenuService.java
Labels: 💻 BE, ✨ feat

#67 [BE] feat #66 메뉴담기 화면 조회 API
  be/src/main/java/com/codesquad/kiosk/controller/MenuController.java
  be/src/main/java/com/codesquad/kiosk/dto/MenuDetailDto.java
  be/src/main/java/com/codesquad/kiosk/dto/OptionCategoryDto.java
  be/src/main/java/com/codesquad/kiosk/repository/MenuRepository.java
  be/src/main/java/com/codesquad/kiosk/service/MenuService.java
Labels: 💻 BE, ✨ feat

#64 [BE] 주문 api 구현
  be/src/main/java/com/codesquad/kiosk/domain/Order.java
  be/src/main/java/com/codesquad/kiosk/domain/OrderMenu.java
  be/src/main/java/com/codesquad/kiosk/dto/OrderItem.java
  be/src/main/java/com/codesquad/kiosk/dto/OrderNumberCreatorDto.java
  be/src/main/java/com/codesquad/kiosk/dto/OrderRequestDto.java
  be/src/main/java/com/codesquad/kiosk/repository/OrderRepository.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ✨ feat

#70 [BE] feat #69: 영수증 조회 api 구현
  be/src/main/java/com/codesquad/kiosk/controller/OrderController.java
  be/src/main/java/com/codesquad/kiosk/dto/ReceiptDto.java
  be/src/main/java/com/codesquad/kiosk/dto/ReceiptItemDto.java
  be/src/main/java/com/codesquad/kiosk/repository/OrderRepository.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ✨ feat

#74 [BE] feat #59: 카드 결제 실패
  be/src/main/java/com/codesquad/kiosk/controller/OrderController.java
  be/src/main/java/com/codesquad/kiosk/dto/PaymentFailedDto.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ✨ feat

#73 feat #59: 현금결제 ResponseDto 생성
  be/src/main/java/com/codesquad/kiosk/dto/CashPaymentResponseDto.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ✨ feat

#75 [BE] feat #59: 카드 결제
  be/src/main/java/com/codesquad/kiosk/dto/CardPaymentResponseDto.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ✨ feat

#76 fix #59: merge 수정
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, 🛠️ fix

#77 [BE] #59 결제/주문 api 구현 완료
  be/src/main/java/com/codesquad/kiosk/controller/OrderController.java
  be/src/main/java/com/codesquad/kiosk/dto/CardPaymentResponseDto.java
  be/src/main/java/com/codesquad/kiosk/dto/PaymentFailedDto.java
  be/src/main/java/com/codesquad/kiosk/repository/OrderRepository.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ✨ feat, ⚙️ refactor, 🛠️ fix

#78 [BE] #59 결제로직 수정
  be/src/main/java/com/codesquad/kiosk/controller/OrderController.java
  be/src/main/java/com/codesquad/kiosk/dto/CardPaymentResponseDto.java
  be/src/main/java/com/codesquad/kiosk/dto/OrderRequestDto.java
  be/src/main/java/com/codesquad/kiosk/dto/PaymentResponseDto.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ⚙️ refactor, 🛠️ fix

#82 [FE] feat #68: 결제 기능 - 카드
  fe/public/assets/logo.png
  fe/src/App.tsx
  fe/src/components/Cart/Cart.module.css
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Cart/Timer.module.css
  fe/src/components/Cart/Timer.tsx
  fe/src/components/Loading/Loading.module.css
  fe/src/components/Loading/Loading.tsx
  fe/src/components/Loading/PaymentResult.module.css
  fe/src/components/Loading/PaymentResult.tsx
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Modal/AddMenu.tsx
  fe/src/components/Modal/CardPayment.module.css
  fe/src/components/Modal/CardPayment.tsx
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/Payment.tsx
  fe/src/mocks/handler.ts
Labels: 🧑‍💻 FE, ✨ feat

#79 [FE] feat #72: 현금 결제창 기능 구현과 영수증 화면 UI 작업
  fe/src/App.module.css
  fe/src/App.tsx
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Link.tsx
  fe/src/components/Main/MainArea.module.css
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Modal/AddMenu.tsx
  fe/src/components/Modal/CashPayment.module.css
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/Modal.module.css
  fe/src/components/Modal/Modal.tsx
  fe/src/components/Modal/Payment.tsx
  fe/src/components/Receipt/Receipt.module.css
  fe/src/components/Receipt/Receipt.tsx
  fe/src/components/Route.tsx
Labels: 🧑‍💻 FE, ✨ feat

#83 [FE] fix: 각자 개발한 PR 합친 후 오류 수정
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Modal/AddMenu.tsx
Labels: 🧑‍💻 FE, 🛠️ fix

#86 [BE] refactor #63: getPopularityRanking() 메서드 수정
  be/src/main/java/com/codesquad/kiosk/controller/MenuController.java
  be/src/main/java/com/codesquad/kiosk/repository/MenuRepository.java
  be/src/main/java/com/codesquad/kiosk/service/MenuService.java
Labels: 💻 BE, ⚙️ refactor

#88 [FE] refactor : App 상태 관련 전반적인 리팩터링 및 바뀐 API에 따른 수정
  fe/src/App.tsx
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Modal/AddMenu.tsx
  fe/src/components/Tab/TabMenu.tsx
  fe/src/mocks/handler.ts
  fe/src/utils/types.ts
Labels: 🧑‍💻 FE, ⚙️ refactor, 🛠️ fix

#89 [FE] feat #85: 카드결제 성공시 영수증 연결, 영수증 타이머 구현
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Cart/CartItem.module.css
  fe/src/components/Cart/CartItem.tsx
  fe/src/components/Cart/Timer.tsx
  fe/src/components/Link.tsx
  fe/src/components/Loading/PaymentResult.tsx
  fe/src/components/Main/Card.module.css
  fe/src/components/Modal/CardPayment.module.css
  fe/src/components/Modal/CardPayment.tsx
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/Payment.tsx
  fe/src/components/Receipt/Receipt.tsx
  fe/src/mocks/handler.ts
  fe/src/utils/getRandomDelay.ts
Labels: 🧑‍💻 FE, ✨ feat

#90 [FE] feat : 현금결제 창 기능 관련 작업 진행중
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Modal/CashPayment.tsx
  fe/src/mocks/handler.ts
  fe/src/utils/modifyOrderList.ts
Labels: 🧑‍💻 FE, ✨ feat

#95 [FE] feat #91: BEST상품 표시, 초기 화면 구현
  fe/.gitignore
  fe/src/App.tsx
  fe/src/components/Main/Card.module.css
  fe/src/components/Main/Card.tsx
  fe/src/components/Main/MainArea.tsx
  fe/src/components/Main/Screensaver.module.css
  fe/src/components/Main/Screensaver.tsx
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/Payment.tsx
  fe/src/index.css
  fe/src/mocks/handler.ts
  fe/src/utils/types.ts
Labels: 🧑‍💻 FE, ✨ feat

#96 [FE] feat #80:현금 결제창 및 영수증 화면 기능 작업
  fe/src/App.tsx
  fe/src/components/Cart/Cart.tsx
  fe/src/components/Link.tsx
  fe/src/components/Modal/AddMenu.tsx
  fe/src/components/Modal/CashPayment.tsx
  fe/src/components/Modal/Payment.tsx
  fe/src/components/Receipt/Receipt.tsx
  fe/src/index.tsx
  fe/src/mocks/handler.ts
Labels: 🧑‍💻 FE, ✨ feat

#99 [Be] feat #92 : cors 메서드 추가
  be/src/main/java/com/codesquad/kiosk/config/WebConfig.java
  be/src/main/java/com/codesquad/kiosk/repository/OrderRepository.java
Labels: 💻 BE, ✨ feat

#100 [BE] refactor #69: 영수증 조회 api 리팩토링
  be/src/main/java/com/codesquad/kiosk/dto/ReceiptDto.java
  be/src/main/java/com/codesquad/kiosk/dto/ReceiptOrderNumberDto.java
  be/src/main/java/com/codesquad/kiosk/repository/OrderRepository.java
  be/src/main/java/com/codesquad/kiosk/service/OrderService.java
Labels: 💻 BE, ⚙️ refactor
